# Generated by Django 5.1.6 on 2025-02-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_group_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
