# Generated by Django 5.1.6 on 2025-02-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/cheques')),
                ('payment', models.IntegerField()),
                ('comment', models.TextField(null=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'payments',
                'managed': False,
            },
        ),
    ]
