# Generated by Django 5.1.6 on 2025-02-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'admin',
                'verbose_name_plural': 'admins',
                'db_table': 'admins',
                'managed': False,
            },
        ),
    ]
