# Generated by Django 5.1.6 on 2025-02-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
